import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.core.config import settings
from app.core.middleware import AuthMiddleware
from app.api.v1.router import api_router

# Configure basic logging format
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager handling startup events:
    1. Triggers SQLAlchemy metadata table creation.
    2. Builds/verifies Memori database tables.
    """
    logger.info("Starting up Business Research Copilot API service...")
    
    # Auto-create all SQLAlchemy models in PostgreSQL on startup
    try:
        from app.models import Base
        from app.core.database import engine
        logger.info("Verifying and creating app database tables...")
        Base.metadata.create_all(bind=engine)
        logger.info("Database tables checked and created.")
    except Exception as e:
        logger.critical(f"Failed to auto-create database tables on startup: {e}")
        
    # Trigger Memori SQL schema build
    try:
        from app.services.memory_service import init_memori_db
        init_memori_db()
    except Exception as e:
        logger.error(f"Failed to build Memori tables: {e}")
        
    yield
    
    logger.info("Shutting down Business Research Copilot API service...")
    try:
        from langfuse import get_client
        logger.info("Flushing and shutting down Langfuse telemetry client...")
        get_client().shutdown()
    except Exception as e:
        logger.warning("Failed to shutdown Langfuse telemetry client: %s", e)

app = FastAPI(
    title=settings.PROJECT_NAME,
    lifespan=lifespan,
    openapi_url=f"{settings.API_V1_STR}/openapi.json"
)

# ---------------------------------------------------------------------------
# Auth Middleware
# Validates JWT on every protected route at the HTTP layer.
# Must be added BEFORE CORSMiddleware so that CORSMiddleware wraps it,
# ensuring CORS headers are added to any 401 response generated by this middleware.
# ---------------------------------------------------------------------------
app.add_middleware(AuthMiddleware)

# ---------------------------------------------------------------------------
# CORS Middleware
# Note: CORSMiddleware MUST be added after AuthMiddleware so that CORSMiddleware
# wraps AuthMiddleware, allowing it to intercept all requests first (including OPTIONS)
# and append CORS headers to all responses.
# In production, replace allow_origins with your real domain list.
# ---------------------------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        settings.FRONTEND_ORIGIN,          # e.g. http://localhost:5173 or prod URL
        "http://localhost:5173",           # Vite dev server
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# Include API Router
app.include_router(api_router, prefix=settings.API_V1_STR)

@app.get("/health", tags=["health"])
def health_check():
    """
    Health check endpoint to monitor status of backend API container.
    """
    return {
        "status": "healthy",
        "project": settings.PROJECT_NAME
    }
