from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict):
    # Core attributes
    messages: List[Dict[str, Any]]       # History of chat dialogue turns
    user_id: int                         # The authenticated user's database ID
    chat_id: int                         # Current chat thread identifier
    mode: str                            # Mode: 'research', 'email_draft', 'task_list', or 'general'
    
    # Long-term memory: user facts retrieved from Memori at workflow start
    user_memory_context: Optional[str]   # Pre-formatted string of user memory facts injected into Writer prompt
    
    # Execution states
    next_step: str                       # Tells LangGraph which node to run next
    research_query: Optional[str]        # Formulated search term
    research_findings: List[Dict[str, Any]] # Extracted page summaries and metadata
    draft: Optional[str]                 # Draft output generated by the Writer
    feedback: Optional[str]              # Corrective feedback from the LLM Judge
    critic_loops: int                    # Counts correction iterations (max 3 loops)
    
    # Final response
    final_response: Optional[str]        # Final validated answer returned to user
